#!/usr/bin/env python3
"""Shows everywhere the display order is read."""

print("=" * 70)
print("WHERE IS THE ORDER READ?")
print("=" * 70)
print()

print("1. WEB UI")
print("-" * 70)
print("File: services/web/configuration_page_service.py")
print("Line: 157-174")
print("Code:")
print("  # Load order values from container JSON files")
print("  container_orders = {}")
print("  containers_dir = Path(base_dir) / 'config' / 'containers'")
print("  for container_file in containers_dir.glob('*.json'):")
print("      container_data = json.load(f)")
print("      container_orders[name] = container_data.get('order', 999)")
print("  # Sort by order")
print("  live_containers_list.sort(key=lambda x: container_orders.get(x.get('name', ''), 999))")
print()

print("2. DISCORD STATUS OVERVIEW (/ss)")
print("-" * 70)
print("File: cogs/docker_control.py")
print("Lines: 936, 1312, 3223")
print("Code:")
print("  ordered_servers = sorted(servers, key=lambda s: s.get('order', 999))")
print()

print("3. DISCORD CONTROL CHANNEL")
print("-" * 70)
print("File: cogs/control_ui.py")
print("Lines: 1363, 1476")
print("Code:")
print("  ordered_servers = sorted(servers, key=lambda s: s.get('order', 999))")
print()

print("4. CONFIG SERVICE (server list)")
print("-" * 70)
print("File: services/config/config_service.py")
print("Line: 1496")
print("Code:")
print("  servers.sort(key=lambda s: s.get('order', 999))")
print()

print("=" * 70)
print("SUMMARY")
print("=" * 70)
print()
print("✅ The order is stored EXCLUSIVELY in the JSON files!")
print("✅ Every component reads the 'order' field from the container JSON files")
print("✅ No other source for the order exists any more")
print()
print("To change the order:")
print("  1. Web UI: use the + and - buttons and save")
print("  2. Manually: change the 'order' values in config/containers/*.json")
print()
print("After saving/restarting, the order is the same everywhere right away!")
