#!/usr/bin/env python3
"""Zeigt wo die Reihenfolge überall gelesen wird."""

print("=" * 70)
print("WO WIRD DIE REIHENFOLGE GELESEN?")
print("=" * 70)
print()

print("1. WEB UI")
print("-" * 70)
print("Datei: services/web/configuration_page_service.py")
print("Zeile: 157-174")
print("Code:")
print("  # Load order values from container JSON files")
print("  container_orders = {}")
print("  containers_dir = Path(base_dir) / 'config' / 'containers'")
print("  for container_file in containers_dir.glob('*.json'):")
print("      container_data = json.load(f)")
print("      container_orders[name] = container_data.get('order', 999)")
print("  # Sort by order")
print("  live_containers_list.sort(key=lambda x: container_orders.get(x.get('name', ''), 999))")
print()

print("2. DISCORD STATUS OVERVIEW (/ss)")
print("-" * 70)
print("Datei: cogs/docker_control.py")
print("Zeilen: 936, 1312, 3223")
print("Code:")
print("  ordered_servers = sorted(servers, key=lambda s: s.get('order', 999))")
print()

print("3. DISCORD CONTROL CHANNEL")
print("-" * 70)
print("Datei: cogs/control_ui.py")
print("Zeilen: 1363, 1476")
print("Code:")
print("  ordered_servers = sorted(servers, key=lambda s: s.get('order', 999))")
print()

print("4. CONFIG SERVICE (Server Liste)")
print("-" * 70)
print("Datei: services/config/config_service.py")
print("Zeile: 1496")
print("Code:")
print("  servers.sort(key=lambda s: s.get('order', 999))")
print()

print("=" * 70)
print("ZUSAMMENFASSUNG")
print("=" * 70)
print()
print("✅ Die Reihenfolge ist AUSSCHLIESSLICH in den JSON-Dateien gespeichert!")
print("✅ Jede Komponente liest das 'order' Feld aus den Container JSON-Dateien")
print("✅ Keine andere Quelle für die Reihenfolge existiert mehr")
print()
print("Wenn du die Reihenfolge ändern willst:")
print("  1. Web UI: Benutze + und - Buttons und speichere")
print("  2. Manuell: Ändere 'order' Werte in config/containers/*.json")
print()
print("Die Reihenfolge wird sofort nach dem Speichern/Neustart überall gleich sein!")
