#!/usr/bin/env python3
"""Generate docs/quality/CHECK_PLAN.txt from docs/quality/SECTIONS.txt and the code.

Stage 4 of the quality programme: for every section, the public names a
reviewer has to judge one by one - top-level classes and functions, and the
public methods of public classes, whose definition line lies inside one of the
section's pieces. "Public" means: the name does not start with "_".

The plan used to be written once (2026-09-17) and kept by hand; its line
numbers drifted with every fix, and it listed bare file names although
several files share one ("service.py", "__init__.py"). Generating it from the
code keeps both honest. A name is identified as "path:line name".

Usage:
    python3 scripts/review/check_plan.py            # rewrite CHECK_PLAN.txt
    python3 scripts/review/check_plan.py --section 18   # print one section
"""

import argparse
import ast
import re
import sys
from pathlib import Path

PROJECT = Path(__file__).resolve().parents[2]
SECTIONS = PROJECT / "docs" / "quality" / "SECTIONS.txt"
PLAN = PROJECT / "docs" / "quality" / "CHECK_PLAN.txt"
HEADER = re.compile(r"^## Section (\d+)\s")
PIECE = re.compile(r"^(?P<path>[^:#\s]+\.py):(?P<start>\d+)-(?P<end>\d+)\s*$")

PREAMBLE = """\
# Stage 4 - check plan per section
#
# GENERATED by scripts/review/check_plan.py from SECTIONS.txt and the code -
# do not edit by hand. For every section the public names a review has to
# judge one by one: top-level classes and functions, and the public methods
# of public classes, whose definition lies inside the section's pieces.
#
# THIS PLAN IS A TO-DO LIST, NOT EVIDENCE. Verdicts live in
# docs/quality/reviews/, one report per section and pass; the coverage of a
# report against this plan is computed by scripts/review/coverage.py.
"""


def read_sections():
    """{section number: [(path, start, end), ...]} in file order."""
    sections, current = {}, None
    for line in SECTIONS.read_text(encoding="utf-8").splitlines():
        header = HEADER.match(line)
        if header:
            current = int(header.group(1))
            sections[current] = []
            continue
        piece = PIECE.match(line)
        if piece and current is not None:
            sections[current].append((piece["path"], int(piece["start"]), int(piece["end"])))
    return sections


DEFS = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)


def public_names(path, start, end):
    """[(line, qualified name)] of the public definitions in path[start..end].

    Nested definitions count too, at any depth: Flask routes and security hooks
    are often defined inside a registering function (app/web/routes.py,
    app/web/security.py), decorators wrap an inner function, and some button
    views are classes inside a PRIVATE method (docker_control.py
    PersistentMech*View). A definition is listed when its OWN name is public,
    whatever encloses it; the qualified name shows where it lives.
    """
    tree = ast.parse((PROJECT / path).read_text(encoding="utf-8"))
    found = []

    def visit(body, prefix):
        for node in body:
            if isinstance(node, DEFS):
                qualified = f"{prefix}{node.name}"
                if not node.name.startswith("_") and start <= node.lineno <= end:
                    found.append((node.lineno, qualified))
                visit(node.body, f"{qualified}.")
            elif not isinstance(node, DEFS):
                # if/try/with blocks at the same level can hold definitions too
                for field in ("body", "orelse", "finalbody", "handlers"):
                    inner = getattr(node, field, None)
                    if isinstance(inner, list):
                        visit(inner, prefix)

    visit(tree.body, "")
    return sorted(found)


def section_plan(pieces):
    """The plan lines of one section: ["path:line name", ...]."""
    lines = []
    for path, start, end in pieces:
        lines += [f"{path}:{line} {name}" for line, name in public_names(path, start, end)]
    return lines


def render(sections):
    out = [PREAMBLE]
    for number, pieces in sections.items():
        names = section_plan(pieces)
        size = sum(end - start + 1 for _p, start, end in pieces)
        out.append(f"## Section {number:02d}  ({size} lines, {len(names)} public names)")
        out += [f"[ ] {name}" for name in names]
        out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--section", type=int, help="print the plan of one section only")
    args = parser.parse_args()
    sections = read_sections()
    if args.section is not None:
        print("\n".join(section_plan(sections[args.section])))
        return 0
    PLAN.write_text(render(sections), encoding="utf-8")
    total = sum(len(section_plan(p)) for p in sections.values())
    print(f"{PLAN.relative_to(PROJECT)}: {len(sections)} sections, {total} public names")
    return 0


if __name__ == "__main__":
    sys.exit(main())
